<?php
define('_DB_SERVER_', 'denfish.mysql.ukraine.com.ua');
define('_DB_NAME_', 'denfish_db');
define('_DB_USER_', 'denfish_db');
define('_DB_PASSWD_', 'Jfz2HH6Z');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '1');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', '1edfb101b09183597d1c448bcf60d626');
define('_COOKIE_IV_', 'xBjOpDgp');
define('_PS_CREATION_DATE_', '2015-10-18');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'traTqZuFufxntbxV4bMzSQ6TPJU29kDn');
define('_RIJNDAEL_IV_', '+tG8w1Rog+bjmyVbULEHJg==');
